coverage:
  range: 68..100
  round: down
  precision: 2
  status:
    project:
      default:
        # basic
        target: 68%
        threshold: 5%
        base: auto 
    patch:
      default:
        # basic
        target: 68%
        threshold: 5%
        base: auto    
ignore:
  "experiments"  
